# Comment to be posted on PRs from first-time contributors in your repository
newPRWelcomeComment: |
  Thank you for opening this pull request! 🙌

  These tips will help get your PR across the finish line:

  - If you haven't already, check out the [Contributing Guide](https://unionml.readthedocs.io/en/stable/contributing_guide.html)
  - Sign off your commits (Reference: [DCO Guide](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md)).

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉

# Comment to be posted on first-time issues
newIssueWelcomeComment: >
  Thank you for opening your first issue here! 🛠
