repos:
- repo: https://github.com/PyCQA/flake8
  rev:  4.0.1
  hooks:
    - id: flake8
- repo: https://github.com/psf/black
  rev:  22.3.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/isort
  rev:  5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: check-yaml
      args: [ "--unsafe" ]
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.8.0.4
  hooks:
  - id: shellcheck
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
      entry: mypy unionml tests
      files: (^unionml/|^tests)
      exclude: (^docs/)
      pass_filenames: false
      additional_dependencies:
      - types-requests
- repo: local
  hooks:
  - id: convert-myst-to-ipynb
    name: convert myst markdown to jupyter notebooks
    language: system
    entry: python -m scripts.myst_to_ipynb
    files: (^docs/tutorials/)
    args: [docs/tutorials, -o, docs/notebooks, -d, docs/source/tutorials]
    pass_filenames: false
